import Head from 'next/head'
// import Image from 'next/image'
import styles from '../styles/Home.module.css'
// import { Squats, ThrillerMoves, HipHop, Excercise1, Excercise2, DanceOff, FunMoves } from '../components'
import Landing1 from '../components/Landing'
import { useEffect, useState } from 'react';
import { motion } from "framer-motion";
import Welcome from '../components/Welcome';
import {BrowserRouter} from 'react-router-dom'
import Warning from '../components/Warning';
import Loader from '../components/Loader'



export default function Home() {
 
  const [isMobile,setisMobile] = useState(false);
 

  useEffect(()=>{
    if(window.innerWidth<=800)
    setisMobile(true)
  },[])
  
  



  return (
    
      <div>
      <Head>
        <title>Threecise</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
        {isMobile?<Warning/>:<Landing1/>}
        

    </div>

  )
}
